export default [
  { ignores: ['dist', 'node_modules', 'dev-dist', 'build', 'playwright-report', 'test-results', 'coverage'] },
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      globals: {
        browser: true,
        node: true,
        es6: true,
        window: true,
        document: true,
        navigator: true,
        console: true,
        localStorage: true,
        // Built-in browser APIs are set to false to prevent overriding (read-only for security consistency)
        setTimeout: false,
        clearTimeout: false,
        setInterval: false,
        clearInterval: false,
        requestAnimationFrame: false,
        cancelAnimationFrame: false,
        confirm: false,
        alert: false,
        fetch: false,
        URL: false,
        location: true,
        Request: true,
        Response: true,
        Headers: true,
        caches: true,
        ExtendableEvent: true,
        FetchEvent: true,
        importScripts: true,
        self: true,
        indexedDB: true,
        IDBDatabase: true,
        IDBObjectStore: true,
        IDBIndex: true,
        IDBCursor: true,
        IDBTransaction: true,
        IDBRequest: true,
        DOMException: true,
        process: true,
      },
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'error',
    },
  },
  {
    files: ['src/**/*.test.{js,jsx}', 'src/setupTests.js'],
    languageOptions: {
      globals: {
        describe: true,
        it: true,
        test: true,
        expect: true,
        beforeEach: true,
        afterEach: true,
        beforeAll: true,
        afterAll: true,
        vi: true,
      },
    },
  },
];
